version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src/laravel:/var/www/html
    env_file:
      - .env
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: nginx-web
    ports:
      - "80:80" # expose only nginx to host
    volumes:
      - ./src/laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
